services:
  postgres:
    image: postgres:15-alpine
    container_name: terra_magna_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - terra_magna_network

  app:
    build: .
    container_name: terra_magna_app
    ports:
      - "${APP_PORT}:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      PORT: 3000
      MODE: ${MODE}
    depends_on:
      - postgres
    networks:
      - terra_magna_network

volumes:
  postgres_data:

networks:
  terra_magna_network:
